### ISSUE TITLE
[Bug]: Installation Fails when installing Pandas

### ISSUE THREAD

**Issue by JDaniel41** [American-Soccer-Analysis/itscalledsoccer#133]
### What happened?

When I run `pip install itscalledsoccer`, the command fails when trying to install Pandas v1.3.1. Currently, I have Pandas v2.0.1 installed. I tried installing Pandas v1.3.1 manually and it still doesn't work. I also have numpy v1.24.3 installed, and can use that just fine.

### Version

0.2.0

### What version of Python are you using?

Python 3.11.x

### What operating system are you using?

MacOS

### Relevant log output

```sh
> pip install pandas==1.3.1
Collecting pandas==1.3.1
  Using cached pandas-1.3.1.tar.gz (4.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/Users/jonathanmdaniel/miniconda3/envs/asa-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/jonathanmdaniel/miniconda3/envs/asa-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jonathanmdaniel/miniconda3/envs/asa-env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v1/y50fhq4d5g5bzjysgkkts17h0000gn/T/pip-build-env-_y6al_bi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v1/y50fhq4d5g5bzjysgkkts17h0000gn/T/pip-build-env-_y6al_bi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/v1/y50fhq4d5g5bzjysgkkts17h0000gn/T/pip-build-env-_y6al_bi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/v1/y50fhq4d5g5bzjysgkkts17h0000gn/T/pip-build-env-_y6al_bi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by bgrnwd** [comment]
@JDaniel41 Thanks for reporting this!

There a are a number of dependencies that are outdated and don't support Python 3.11. I've gone ahead and updated them in #134. I've also added dependabot so these dependencies will automatically be updated in the future.
