### ISSUE TITLE
[Bug]: No Module named cachecontrol

### ISSUE THREAD

**Issue by nielsenz** [American-Soccer-Analysis/itscalledsoccer#18]
### What happened?

After successfully installing itscalledsoccer on anaconda, when running the following installation code in python, ran into the following error.

`from itscalledsoccer.client import AmericanSoccerAnalysis

asa_client = AmericanSoccerAnalysis()`

`from itscalledsoccer.client import AmericanSoccerAnalysis
Traceback (most recent call last):

  File "<ipython-input-4-8c319c8c7d6a>", line 1, in <module>
    from itscalledsoccer.client import AmericanSoccerAnalysis

  File "/Users/nielsenz/anaconda3/lib/python3.7/site-packages/itscalledsoccer/client.py", line 7, in <module>
    from cachecontrol import CacheControl

ModuleNotFoundError: No module named 'cachecontrol'`

### Version

0.1.1

### What version of Python or R are you using?

Python 3.7.x

### What operating system are you using?

MacOS

### Relevant log output

```shell
from itscalledsoccer.client import AmericanSoccerAnalysis
Traceback (most recent call last):

  File "<ipython-input-4-8c319c8c7d6a>", line 1, in <module>
    from itscalledsoccer.client import AmericanSoccerAnalysis

  File "/Users/nielsenz/anaconda3/lib/python3.7/site-packages/itscalledsoccer/client.py", line 7, in <module>
    from cachecontrol import CacheControl

ModuleNotFoundError: No module named 'cachecontrol'
```

**Comment by nielsenz** [comment]
Thanks for providing the data!
